version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 100
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 100
      runas: ec2-user
