version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the dist folder
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
# Include only the files required for your application to run.
artifacts:
  files:
    - appspec.yml
    - index.js
    - client/**/*
    - public/**/*
    - scripts/**/*
    - server/**/*
    - webpack.config.js
    - package.json
    - package-lock.json
    - node_modules/**/*
    - .ebextensions/**/*
